apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ece1779
data:
  DATABASE_URL: "postgres://postgres:postgres@postgres:5432/cloud_db?sslmode=disable"
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: ece1779
type: Opaque
stringData:
  POSTGRES_DB: cloud_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  
