version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: cloud_db
      POSTGRES_USER: postgres
      # TODO: replace later
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../../db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ../../db/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cloud_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ../../services/api
    environment:
      #TODO: change later
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/cloud_db?sslmode=disable
      PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  worker:
    build:
      context: ../../services/worker
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/cloud_db?sslmode=disable
      POLL_MS: "1000"
      WORK_MS: "3000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
