name: build-and-deploy

on:
  push:
    branches: ["main"]

env:
  REGISTRY: registry.digitalocean.com
  NAMESPACE: ece1779

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute image tags
        id: vars
        run: |
          echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "API_IMAGE=${{ env.REGISTRY }}/${{ secrets.DOCR_NAME }}/api:${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "WORKER_IMAGE=${{ env.REGISTRY }}/${{ secrets.DOCR_NAME }}/worker:${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login --expiry-seconds 1200

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push api
        uses: docker/build-push-action@v6
        with:
          context: services/api
          file: services/api/Dockerfile
          push: true
          tags: ${{ steps.vars.outputs.API_IMAGE }}

      - name: Build and push worker
        uses: docker/build-push-action@v6
        with:
          context: services/worker
          file: services/worker/Dockerfile
          push: true
          tags: ${{ steps.vars.outputs.WORKER_IMAGE }}

      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl -n ${{ env.NAMESPACE }} apply -f k8s/

          kubectl -n ${{ env.NAMESPACE }} set image deployment/api api=${{ steps.vars.outputs.API_IMAGE }}
          kubectl -n ${{ env.NAMESPACE }} set image deployment/worker worker=${{ steps.vars.outputs.WORKER_IMAGE }}

          kubectl -n ${{ env.NAMESPACE }} rollout status deployment/api --timeout=180s
          kubectl -n ${{ env.NAMESPACE }} rollout status deployment/worker --timeout=180s

      - name: Show status
        run: |
          kubectl -n ${{ env.NAMESPACE }} get pods -o wide
          kubectl -n ${{ env.NAMESPACE }} get svc
